version: '3'
services: 
  # NOTE: app/docker-compose.app.yml で実際にビルドを行う
  client:
    tty: true
    volumes:
      # NOTE: ビルド結果を保存するフォルダ
      - type: bind
        source: ~/Documents/archives
        target: /archives
    environment:
      - SSH_HOST_NAME
      - SSH_HOST_ADDRESS
      - SSH_HOST_PASSWORD
      - REPOSITORY_ROOT_PATH
      - TO_HOST_BUILD_ROOT_PATH
      - TO_DOCKER_BUILD_ROOT_PATH=/archives
      - COMPOSE_HTTP_TIMEOUT=1000
      - IS_DOCKER=true
      - GITHUB_ENV
      - GITHUB_WORKSPACE
      - PLATFORM
      - FASTLANE_PASSWORD
      - CURRENT_GIT_BRANCH
