require_relative './service'
require_relative '../../system/configs/config'

platform :ios do
  desc 'ストアへアップロード'
  lane :upload_to_store do |options|
    config = System::Configs::Config.load_config.store.ios
    api_key = app_store_connect_api_key(
      key_id: config.store_key_id,
      issuer_id: config.store_issuer_id,
      key_filepath: File.expand_path("./build/ios/cartificate/#{config.store_auth_key}")
    )

    Store::IOS::Service.new.upload(
      options[:env],
      lambda { |ipa_path, author_email, app_id, app_version, metadata_path, screenshots_path|
        deliver(
          api_key: api_key,
          ipa: ipa_path,
          username: author_email,
          app_identifier: app_id,
          app_version: app_version.to_s,
          metadata_path: metadata_path,
          screenshots_path: screenshots_path,
          force: true,
          automatic_release: false,
          skip_metadata: false,
          skip_screenshots: false,
          skip_app_version_update: true,
          overwrite_screenshots: true
        )
      }
    )
  end
end
