require_relative '../unity/project'
require_relative '../system/project'

lane :execute_on_host do |options|
  sh("sshpass -p #{ENV.fetch('SSH_HOST_PASSWORD')} ssh #{ENV.fetch('SSH_HOST_NAME')}@#{ENV.fetch('SSH_HOST_ADDRESS')} \"#{options[:cmd]}\"")
end

lane :execute_on_host_on_client_repo do |options|
  execute_on_host(cmd: "cd #{Unity::Project.new(System::Project.root_path).project_root_path} && #{options[:cmd]}")
end
